# Extra autostart processes
# exec-once = uwsm app -- my-service

# Controls idle/sleep settings.
exec-once = uwsm-app -- hypridle
# Wayland notification daemon
exec-once = uwsm-app -- mako
# Waybar settings
exec-once = uwsm-app -- waybar
# ???
exec-once = uwsm-app -- fcitx5
# Wayland background
exec-once = uwsm-app -- swaybg -i ~/Wallpapers/cats.png -m fill
# Show volume status with swayOSD
exec-once = uwsm-app -- swayosd-server
# Set polkit authentication agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all
