# I have switched ALT with SUPER! see input.conf
# Application bindings
$terminal = uwsm app -- $TERMINAL
$browser = launch-browser
$mainMod = SUPER

# window navigation
# Move focus with mainMod + arrow keys
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r bind = $mainMod, K, movefocus, u bind = $mainMod, J, movefocus, d 

# Switch panes 
bind = $mainMod CTRL, H, movewindow, l
bind = $mainMod CTRL, L, movewindow, r
bind = $mainMod CTRL, K, movewindow, u
bind = $mainMod CTRL, J, movewindow, d

bindd = $mainMod, return, Terminal, exec, $terminal --dir="$(cmd-terminal-cwd)"
bindd = $mainMod, F, File manager, exec, launch-tui yazi
bindd = $mainMod, B, Browser, exec, $browser
bindd = $mainMod SHIFT, B, Browser (private), exec, $browser --private
bindd = $mainMod, T, Activity, exec, launch-tui btop
bindd = $mainMod, D, Docker, exec, launch-tui lazydocker
bindd = $mainMod, G, Signal, exec, launch-or-focus signal "uwsm app -- signal-desktop"
bindd = $mainMod, O, Obsidian, exec, launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = $mainMod, A, ChatGPT, exec, launch-webapp "https://chatgpt.com"
bindd = $mainMod, E, Email, exec, launch-webapp "https://mail.google.com/mail/u/0/##inbox"

# change close window to be i3 consistent
bind = $mainMod SHIFT, Q, killactive 

# shutdown hotkey
bindd = $mainMod SHIFT, E, Shutdown, exec, shutdown now

# MEDIA
# Only display the OSD on the currently focused monitor
$osdclient = swayosd-client --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"

# Laptop multimedia keys for volume and LCD brightness (with OSD)
bindeld = ,XF86AudioRaiseVolume, Volume up, exec, $osdclient --output-volume raise
bindeld = ,XF86AudioLowerVolume, Volume down, exec, $osdclient --output-volume lower
bindeld = ,XF86AudioMute, Mute, exec, $osdclient --output-volume mute-toggle
bindeld = ,XF86AudioMicMute, Mute microphone, exec, $osdclient --input-volume mute-toggle
bindeld = ,XF86MonBrightnessUp, Brightness up, exec, $osdclient --brightness raise
bindeld = ,XF86MonBrightnessDown, Brightness down, exec, $osdclient --brightness lower

# remember that I have switched alt with SUPER, so this is actually windows key
# Precise 1% multimedia adjustments with Alt modifier
bindeld = ALT, XF86AudioRaiseVolume, Volume up precise, exec, $osdclient --output-volume +1
bindeld = ALT, XF86AudioLowerVolume, Volume down precise, exec, $osdclient --output-volume -1
bindeld = ALT, XF86MonBrightnessUp, Brightness up precise, exec, $osdclient --brightness +1
bindeld = ALT, XF86MonBrightnessDown, Brightness down precise, exec, $osdclient --brightness -1

# Requires playerctl
bindld = , XF86AudioNext, Next track, exec, $osdclient --playerctl next
bindld = , XF86AudioPause, Pause, exec, $osdclient --playerctl play-pause
bindld = , XF86AudioPlay, Play, exec, $osdclient --playerctl play-pause
bindld = , XF86AudioPrev, Previous track, exec, $osdclient --playerctl previous


